export const messageBank = [
  "Bom dia! Como você está?",
  "Tudo bem por aí?",
  "Fala amigo, beleza?",
  "Oi, passando pra dar um oi.",
  "E aí, como vai as coisas?",
  "Boa tarde! Tudo tranquilo?",
  "Viu aquilo que te mandei?",
  "Opa, e aí?",
  "Como foi seu dia hoje?",
  "Tudo certo amigo?",
  "Conseguiu resolver aquilo?",
  "Depois me dá um toque aqui.",
  "Beleza, fico no aguardo.",
  "Tranquillo, sem pressa.",
  "Show de bola!",
  "Combinado então.",
  "Beleza pura.",
  "Opa, maravilha.",
  "Que bom saber!",
  "Entendi, faz sentido.",
  "Vou ver aqui e te aviso.",
  "Pode falar agora?",
  "Tá ocupado?",
  "Depois a gente se fala então.",
  "Abraço!",
  "Tchau tchau.",
  "Até mais tarde.",
  "Valeu!",
  "Obrigado hein.",
  "Magina, que isso.",
  "Disponha sempre.",
  "Sim, com certeza.",
  "Não, ainda não.",
  "Talvez mais tarde.",
  "Vou pensar e te falo.",
  "Complicado né?",
  "Pois é, bizarro.",
  "Engraçado isso.",
  "Olha só!",
  "Incrível.",
  "Pensa bem.",
  "Vale a pena?",
  "Acho que sim.",
  "Acho que não viu.",
  "Sério mesmo?",
  "Caramba!",
  "Nossa, nem me diga.",
  "Tô sabendo.",
  "Me conta mais.",
  "Interessante.",
  "Pode ser.",
  "Vamos fazer assim...",
  "Tive uma ideia.",
  "O que você acha?",
  "Qual sua opinião?",
  "Manda a boa.",
  "Tô por aqui qualquer coisa.",
  "Só me chamar.",
  "Beleza, fechou.",
  "Tudo ótimo.",
  "Nada de novo por aqui.",
  "E a família, como tá?",
  "Trabalhando muito?",
  "Hoje tá corrido né?",
  "O tempo voa.",
  "Já é sexta-feira?",
  "Quase lá.",
  "Boa semana pra nós.",
  "Bom final de semana!",
  "Aproveita bastante.",
  "Descansa aí.",
  "Tamo junto.",
  "Forte abraço.",
  "Precisando é só gritar.",
  "Ouviu o áudio?",
  "Viu a foto?",
  "Mandei o documento lá.",
  "Confere por favor.",
  "Tá na mão.",
  "Prontinho.",
  "Finalizado aqui.",
  "Esqueci de comentar...",
  "Lembrei de você hoje.",
  "Apareceu uma oportunidade.",
  "Bora marcar um café?",
  "Faz tempo que não nos vemos.",
  "Saudades!",
  "Como foi a viagem?",
  "Tudo certo no trabalho?",
  "Novidades?",
  "Conta as novas.",
  "Nada demais.",
  "Só o básico.",
  "Levando a vida.",
  "De boa.",
  "Curtindo o dia.",
  "Solzão hoje né?",
  "Chuvinha chata.",
  "Friozinho bom.",
  "Calor demais!",
  "Nem me fale.",
  "Pois é amigo.",
  "É a vida.",
  "Fazer o que né?",
  "Segue o baile.",
  "Bola pra frente.",
  "Ânimo!",
  "Vai dar tudo certo.",
  "Acredite.",
  "Fé no pai.",
  "Gratidão.",
  "Sempre.",
  "Exatamente.",
  "Concordo plenamente.",
  "Discordo um pouco.",
  "Tanto faz.",
  "Você que sabe.",
  "Manda aí.",
  "Tô ouvindo.",
  "Espera um pouco.",
  "Já volto.",
  "Tô dirigindo.",
  "Tô em reunião.",
  "Depois te ligo.",
  "Pode ligar.",
  "Tô livre.",
  "Bora!",
  "Partiu.",
  "Vamos nessa.",
  "Com certeza.",
  "Sem dúvida.",
  "Realmente.",
  "Fato.",
  "Verdade.",
  "Mentira!",
  "Sério?",
  "Não acredito.",
  "Passado.",
  "Chocado.",
  "Rindo muito.",
  "Kkkkkk",
  "Putz.",
  "Eita.",
  "Aff.",
  "Aiai.",
  "Bom demais.",
  "Ruim não tá.",
  "Podia ser pior.",
  "Melhor impossível.",
  "Top!",
  "Diferenciado.",
  "Qualidade.",
  "Bacana.",
  "Legal.",
  "Massa.",
  "Irado.",
  "Animal.",
  "Fenomenal.",
  "Estupendo.",
  "Maravilhoso.",
  "Fantástico.",
  "Excelente.",
  "Perfeito.",
  "Gostei muito.",
  "Aprovado.",
  "Recomendo.",
  "Legal seu perfil.",
  "Viu os status lá?",
  "Postei uma coisa legal.",
  "Dá uma olhada.",
  "Depois a gente conversa mais.",
  "Vou sair agora.",
  "Até.",
  "Fui.",
  "Abraços.",
  "Fica com Deus.",
  "Amém.",
  "Igualmente.",
  "Pra você também.",
  "Sucesso!",
  "Boa sorte.",
  "Parabéns!",
  "Feliz aniversário!",
  "Tudo de bom.",
  "Muitos anos de vida.",
  "Saúde e paz.",
  "O resto a gente corre atrás.",
  "É isso.",
  "Basicamente.",
  "Resumindo...",
  "Enfim.",
  "Bom repouso.",
  "Dorme bem.",
  "Sonha com os anjos.",
  "Bom dia, flores do dia.",
  "Acorda aí!",
  "Já é dia.",
  "Café tá pronto?",
  "Queria um docinho agora.",
  "Fome de leão.",
  "Almoçou?",
  "O que tem de bom hoje?",
  "Comida caseira é melhor.",
  "Vou pedir um lanche.",
  "Pizza hoje?",
  "Bora comer algo.",
  "Tô cheio.",
  "Comi demais.",
  "Dieta amanhã.",
  "Promessa é dívida.",
  "Vou na academia.",
  "Preguiça bateu.",
  "Foco!",
  "Determinação.",
  "Meta batida.",
  "Trabalho duro.",
  "Recompensa vem.",
  "Valeu a pena.",
  "Tô exausto.",
  "Preciso de férias.",
  "Onde vamos nas próximas?",
  "Praia ou campo?",
  "Eu prefiro mar.",
  "Montanha é bom também.",
  "Ar puro.",
  "Natureza.",
  "Paz de espírito.",
  "Equilíbrio.",
  "Meditação.",
  "Yoga.",
  "Mente sã, corpo são.",
  "Leitura em dia?",
  "Qual livro tá lendo?",
  "Me indica um filme.",
  "Série nova no Netflix?",
  "Vi uma muito boa.",
  "Assiste lá.",
  "Te indico.",
  "Legal né?",
  "Diferente.",
  "Meio estranho.",
  "Não entendi o final.",
  "Spoiler kkk.",
  "Vou ver agora.",
  "Tchau, vou ver filme.",
  "Pipoca pronta.",
  "Cinema final de semana?",
  "Vamos marcar.",
  "Tô dentro.",
  "Pena que não posso.",
  "Fica pra próxima.",
  "Sem falta hein.",
  "Pode cobrar.",
  "Eu cobro mesmo.",
  "Kkkk folgado.",
  "Brincadeira.",
  "Leve na esportiva.",
  "Sem estresse.",
  "Paz e amor.",
  "Vibe boa.",
  "Energia positiva.",
  "Afaste o que faz mal.",
  "Seja luz.",
  "Brilhe.",
  "Voa!",
  "O céu é o limite.",
  "Pense grande.",
  "Comece pequeno.",
  "Mas comece.",
  "Não pare.",
  "Persista.",
  "Resista.",
  "Vença.",
  "Vitorioso.",
  "Campeão.",
  "Orgulho de você.",
  "Mandou bem.",
  "Fera demais.",
  "Mestre.",
  "Genio.",
  "Sabio.",
  "Aprendendo sempre.",
  "Evolução.",
  "Crescimento.",
  "Mudança é necessária.",
  "Adaptar é preciso.",
  "Novos ares.",
  "Ciclos se fecham.",
  "Novos começam.",
  "Seja grato pelo que passou.",
  "Ansioso pelo que virá.",
  "O futuro é agora.",
  "Viva o presente.",
  "Carpe diem.",
  "Aproveite o momento.",
  "Não deixe pra depois.",
  "O amanhã pode não chegar.",
  "Filosófico hoje hein kkk.",
  "Acordei inspirado.",
  "Poeta kkk.",
  "Boa essa.",
  "Gostei da frase.",
  "Vou anotar.",
  "Copiei.",
  "Colou.",
  "Entendido.",
  "Câmbio desligo.",
  "Rádio amador kkk.",
  "Zuêra não para.",
  "Bom humor é tudo.",
  "Sorria mais.",
  "O mundo agradece.",
  "Seja gentil.",
  "Educação vem de berço.",
  "Respeito é bom e eu gosto.",
  "Tamo aqui pra somar.",
  "Multiplicar também.",
  "Dividir só o que é bom.",
  "Subtrair a negatividade.",
  "Matemática da vida.",
  "Fácil não é.",
  "Mas é possível.",
  "Tudo passa.",
  "Inclusive o café kkk.",
  "Vou tomar um agora.",
  "Expressinho.",
  "Capuccino.",
  "Com pão de queijo.",
  "Delícia.",
  "Quero também.",
  "Vem buscar.",
  "Longe demais kkk.",
  "Fica pra quando você vier.",
  "Bora marcar.",
  "Semana que vem talvez.",
  "Vou olhar a agenda.",
  "Agenda lotada kkk.",
  "Importante ele.",
  "Nada, correria mesmo.",
  "Sei como é.",
  "Vida de adulto.",
  "Boleto não para de chegar.",
  "Triste realidade kkk.",
  "Rir pra não chorar.",
  "É o jeito.",
  "Mas vamos que vamos.",
  "Desistir jamais.",
  "Força na peruca.",
  "Simbora.",
  "Tchau, beijo.",
  "Outro.",
  "Fui mesmo.",
  "Fica na paz.",
  "Valeu amigo.",
  "É nós.",
  "Abraços fortes.",
  "Se cuida.",
  "Juízo hein.",
  "Sempre kkk.",
  "Duvido.",
  "Acredita em mim.",
  "Tô tentando.",
  "Dá um voto de confiança.",
  "Vou pensar.",
  "Chato kkk.",
  "Você que é.",
  "Kkkkk brincadeira.",
  "Eu sei relaxa.",
  "Tamo junto demais.",
  "Parceria forte.",
  "Fechamento.",
  "Irmandade.",
  "Considero muito.",
  "Recíproco.",
  "Tmj.",
  "Forte abraço mesmo.",
  "Aquele abraço.",
  "Viu o jogo ontem?",
  "Meu time ganhou!",
  "O meu perdeu, que raiva.",
  "Futebol é assim.",
  "Zebrou bonito.",
  "O juiz roubou kkk.",
  "Sempre culpa do juiz.",
  "Pênalti claro.",
  "Vibe torcedor.",
  "Grito de gol.",
  "Bandeira estendida.",
  "Paixão nacional.",
  "Samba e futebol.",
  "Brasilzão.",
  "Orgulho de ser brasileiro.",
  "Às vezes nem tanto kkk.",
  "Mas a gente ama.",
  "Terrinha boa.",
  "Povo acolhedor.",
  "Comida sem igual.",
  "Tempero brazuca.",
  "Feijoada no capricho.",
  "Churrasquinho.",
  "Farofa.",
  "Vou parar de falar de comida.",
  "Tô ficando com fome kkk.",
  "Kkkk eu também.",
  "Fui almoçar.",
  "Bom apetite.",
  "Valeu!",
  "Até.",
  "Opa, e os planos pro feriado?",
  "Vai viajar?",
  "Vou ficar de bobeira.",
  "Cinema, pipoca e cama.",
  "Melhor programa.",
  "Concordo.",
  "Às vezes faz falta sair.",
  "Ver gente.",
  "Socializar.",
  "Introvertido kkk.",
  "Eu sou um pouco.",
  "Nem parece.",
  "WhatsApp engana kkk.",
  "Pessoalmente sou tímido.",
  "Sei kkk.",
  "É sério!",
  "Vou fingir que acredito.",
  "Chatonildo kkk.",
  "Divertido eu.",
  "Modesto também.",
  "Kkkk faz parte.",
  "Autoestima é tudo.",
  "Isso aí.",
  "Se ame.",
  "Primeiro você.",
  "Depois os outros.",
  "Não é egoísmo.",
  "É amor próprio.",
  "Certíssimo.",
  "Falou tudo.",
  "Mitou.",
  "Kkk valeu.",
  "Tô indo lá.",
  "Até mais amigo.",
  "Valeu pelo papo.",
  "Gostei muito.",
  "Sempre bom falar com você.",
  "Digo o mesmo.",
  "Abração.",
  "Falou!",
  "Opa, tá por aí?",
  "Bora bater um papo rápido?",
  "Tenho uma novidade pra te contar.",
  "Adivinha quem apareceu hoje?",
  "Você não vai acreditar nisso.",
  "Me liga quando puder, é importante.",
  "Tô te esperando no local combinado.",
  "Não esquece de trazer aquilo.",
  "Amanhã o dia vai ser longo.",
  "Já fez seus planos pra hoje?",
  "Tava lembrando daquela vez...",
  "Ainda tá valendo aquela oferta?",
  "O tempo hoje tá meio estranho né?",
  "Prefiro o frio do que esse calor todo.",
  "Sabe onde posso encontrar um lugar bom pra comer?",
  "Vi uma promoção incrível e lembrei de você.",
  "O que você tá achando do mercado ultimamente?",
  "As coisas estão mudando muito rápido.",
  "Precisamos nos atualizar sempre.",
  "Foco no objetivo e não nas distrações.",
  "Às vezes o silêncio é a melhor resposta.",
  "Mantenha a calma em todas as situações.",
  "O sucesso é o resultado de pequenos esforços.",
  "Sempre que puder, ajude alguém.",
  "A vida é baseada em conexões verdadeiras.",
  "Fique perto de quem te faz bem.",
  "Evite conflitos desnecessários.",
  "Pense duas vezes antes de falar.",
  "A paciência é uma virtude rara.",
  "Seja a mudança que você quer ver.",
  "Tudo que vai, volta.",
  "Plante o bem para colher o bem.",
  "Não se compare com os outros.",
  "Cada um tem seu próprio tempo.",
  "Respeite o seu processo.",
  "Amanhã é um novo dia, com novas chances.",
  "Durma com ideias e acorde com atitudes.",
  "Seja protagonista da sua própria história.",
  "Não tenha medo de errar, tenha medo de não tentar.",
  "O erro é apenas um aprendizado no caminho.",
  "Persista até conseguir o que deseja.",
  "Nunca é tarde para recomeçar.",
  "Siga sua intuição, ela raramente falha.",
  "Confie no seu potencial.",
  "Você é capaz de muito mais do que imagina.",
  "Dê o seu melhor todos os dias.",
  "A constância vence o talento.",
  "Trabalhe enquanto eles dormem? Não, descanse também!",
  "O equilíbrio é a chave para a longevidade.",
  "Cuide da sua saúde mental primeiro.",
  "Aprenda a dizer não sem se sentir culpado.",
  "Sua paz vale mais do que qualquer coisa.",
  "Seja grato pelas pequenas vitórias.",
  "Celebre cada passo dado.",
  "Não espere a perfeição para ser feliz.",
  "A felicidade está nas coisas simples.",
  "Um sorriso pode mudar o dia de alguém.",
  "Mande uma mensagem positiva para um amigo.",
  "A gentileza gera gentileza, sempre.",
  "Seja o raio de sol no dia nublado de alguém.",
  "O mundo precisa de mais empatia.",
  "Coloque-se no lugar do outro antes de julgar.",
  "Ouvir é tão importante quanto falar.",
  "Tenha conversas que edifiquem.",
  "Busque conhecimento constantemente.",
  "Leia livros que expandam sua mente.",
  "Aprenda algo novo toda semana.",
  "Desafie-se a sair da zona de conforto.",
  "É lá que o crescimento acontece.",
  "Mantenha a mente aberta para novas ideias.",
  "Não seja escravo de opiniões alheias.",
  "Tenha personalidade e seja autêntico.",
  "A originalidade é o que nos diferencia.",
  "Não tente agradar a todos, é impossível.",
  "Seja fiel aos seus valores.",
  "A integridade é inegociável.",
  "Honre sua palavra acima de tudo.",
  "O caráter se revela nos pequenos detalhes.",
  "Seja humilde, mas saiba o seu valor.",
  "Reconheça seus limites e peça ajuda.",
  "Ninguém cresce sozinho.",
  "Saiba trabalhar em equipe.",
  "Colabore mais e compita menos.",
  "O sucesso coletivo é mais gratificante.",
  "Fortaleça os seus laços familiares.",
  "Família é o nosso porto seguro.",
  "Diga 'eu te amo' enquanto há tempo.",
  "Não guarde mágoas, elas pesam a alma.",
  "O perdão é libertador.",
  "Siga em frente com o coração leve.",
  "Aproveite a jornada, não apenas a meta.",
  "A jornada é onde a vida acontece.",
  "Crie memórias que valham a pena.",
  "Viaje para lugares que nunca foi.",
  "Experimente sabores diferentes.",
  "Ouça músicas de outros estilos.",
  "A arte salva a alma do cotidiano.",
  "Cante no chuveiro como se fosse um show.",
  "Dance na sala sem preocupação.",
  "Ria de si mesmo e da vida.",
  "O riso é o melhor remédio natural.",
  "Mantenha a criança viva dentro de você.",
  "Curiosidade é o combustível da criatividade.",
  "Pergunte o porquê de tudo.",
  "Não aceite respostas rasas.",
  "Aprofunde-se nos temas que gosta.",
  "Seja um especialista em ser você mesmo.",
  "O mundo é um reflexo do que sentimos.",
  "Mude seu interior e o exterior mudará.",
  "Acredite na lei da atração.",
  "Visualize seus sonhos como realidade.",
  "Aja como se o sucesso já fosse seu.",
  "Prepare-se para as oportunidades.",
  "A sorte é o encontro da preparação com a chance.",
  "Esteja atento aos sinais do universo.",
  "Nada acontece por acaso.",
  "Tudo tem um propósito maior.",
  "Confie no fluxo da vida.",
  "Relaxe e deixe as coisas acontecerem.",
  "Não controle o incontrolável.",
  "Foque no que está ao seu alcance.",
  "Faça a sua parte e deixe o resto.",
  "O universo conspira a favor de quem age.",
  "Seja um fazedor e não apenas um falador.",
  "A execução separa os sonhadores dos realizadores.",
  "Menos planejamento e mais ação controlada.",
  "Itere rápido e aprenda com o feedback.",
  "A perfeição é inimiga da conclusão.",
  "Feito é melhor que perfeito.",
  "Mas faça com excelência o que puder.",
  "Detalhes fazem a diferença no final.",
  "Seja caprichoso em tudo que se propõe.",
  "A qualidade do seu trabalho diz quem você é.",
  "Construa uma reputação sólida.",
  "A confiança demora pra ganhar e segundos pra perder.",
  "Seja transparente e honesto.",
  "Fale a verdade mesmo que doa.",
  "A mentira tem pernas curtas.",
  "A verdade sempre aparece, cedo ou tarde.",
  "Viva com transparência total.",
  "Seja luz por onde passar.",
  "Ilumine o caminho dos outros.",
  "Compartilhe seu brilho sem medo.",
  "Há espaço para todos no topo.",
  "Suba e leve outros com você.",
  "A generosidade é a maior riqueza.",
  "Doe seu tempo e seu talento.",
  "O retorno vem de formas inesperadas.",
  "Seja um canal de bênçãos.",
  "A vida é uma troca constante.",
  "Dê sem esperar receber nada em troca.",
  "A recompensa está no ato de dar.",
  "Sinta a alegria de ser útil.",
  "Encontre o seu propósito de vida.",
  "O que te faz acordar com brilho nos olhos?",
  "Siga sua paixão e o dinheiro virá.",
  "O trabalho não é um fardo se você ama.",
  "Encontre prazer nas tarefas diárias.",
  "Faça tudo com amor e dedicação.",
  "O amor transforma qualquer atividade.",
  "Seja apaixonado por viver.",
  "Cada respiração é um presente.",
  "Agradeça por estar vivo hoje.",
  "A vida é curta demais para lamentar.",
  "Foque no que você tem e não no que falta.",
  "A escassez está na mente, a abundância também.",
  "Treine seus olhos para ver o lado bom.",
  "O otimismo é uma escolha consciente.",
  "Seja um eterno aprendiz da vida.",
  "O conhecimento é a única coisa que não tiram de você.",
  "Invista em si mesmo constantemente.",
  "Seu maior ativo é o seu cérebro.",
  "Cuide bem da sua máquina biológica.",
  "Coma bem, durma bem e se exercite.",
  "Seu corpo é o seu templo sagrado.",
  "Respeite os sinais de cansaço.",
  "Saber parar é tão vital quanto saber agir.",
  "A quietude é necessária para a clareza.",
  "Encontre momentos de solitude.",
  "Conheça a si mesmo profundamente.",
  "A jornada interior é a mais fascinante.",
  "Descubra seus medos e os enfrente.",
  "Atrás do medo está a sua liberdade.",
  "Seja corajoso diante das adversidades.",
  "A coragem não é ausência de medo.",
  "É agir apesar do medo existente.",
  "Seja forte e corajoso sempre.",
  "O mundo pertence aos audazes.",
  "Arrisque-se em novos empreendimentos.",
  "A vida é uma grande aventura.",
  "Não seja apenas um espectador.",
  "Entre na arena e lute seus combates.",
  "As cicatrizes provam que você viveu.",
  "Tenha orgulho da sua trajetória.",
  "Cada obstáculo te tornou mais forte.",
  "A resiliência é a sua maior aliada.",
  "Cia se sete vezes, levante-se oito.",
  "O fracasso é apenas um degrau pro sucesso.",
  "Mantenha a visão no objetivo final.",
  "Não se perca nos detalhes irrelevantes.",
  "Simplifique sua vida ao máximo.",
  "O menos é mais em quase tudo.",
  "Elimine o excesso e foque no essencial.",
  "Minimalismo mental e material.",
  "Limpezas periódicas são bem-vindas.",
  "Desapegue do que não serve mais.",
  "Abra espaço para o novo entrar.",
  "A renovação é a lei da natureza.",
  "Observe as estações da sua vida.",
  "Saiba quando é tempo de plantar.",
  "E saiba quando é tempo de colher.",
  "Não queira pular etapas do processo.",
  "O amadurecimento leva tempo.",
  "A paciência recompensa os persistentes.",
  "Confie no tempo de maturação de tudo.",
  "Nada acontece antes da hora certa.",
  "Esteja pronto para quando o momento chegar.",
  "A oportunidade não espera por ninguém.",
  "Agarre-a com as duas mãos quando vê-la.",
  "Seja ágil nas suas decisões importantes.",
  "A paralisia por análise é real.",
  "Confie no seu julgamento rápido.",
  "Você já tem as respostas dentro de si.",
  "Silencie o barulho externo para ouvi-las.",
  "A voz do coração é sussurrada.",
  "A voz do ego é barulhenta e urgente.",
  "Aprenda a diferenciar as duas vozes.",
  "Siga a paz, ela é o melhor guia.",
  "Se não te traz paz, não é pra você.",
  "Proteja sua energia vital.",
  "Não gaste tempo com discussões estéreis.",
  "Ganhar uma briga não significa ter razão.",
  "A paz é mais valiosa que a vitória do ego.",
  "Seja um pacificador nos seus círculos.",
  "Traga harmonia onde houver discórdia.",
  "O diálogo resolve o que a força não pode.",
  "Seja um mestre na arte da comunicação.",
  "Palavras podem curar ou ferir.",
  "Escolha as suas com sabedoria extrema.",
  "Seja um incentivador de pessoas.",
  "Diga o que os outros precisam ouvir para crescer.",
  "Elogie em público e corrija no privado.",
  "A liderança é serviço e exemplo.",
  "Lidere a si mesmo antes de liderar outros.",
  "Seja o capitão da sua própria alma.",
  "Navegue com propósito em direção ao horizonte.",
  "O vento sopra a favor de quem sabe onde vai.",
  "Não fique à deriva nas circunstâncias.",
  "Assuma o controle do leme da sua vida.",
  "Você é o arquiteto do seu destino.",
  "Construa algo de que se orgulhe.",
  "Deixe um legado positivo para o mundo.",
  "Como você quer ser lembrado?",
  "Viva de forma a responder essa pergunta hoje.",
  "Faça a diferença na vida de alguém agora.",
  "Uma pequena ação pode ter um grande impacto.",
  "Efeito borboleta nas relações humanas.",
  "Tudo que fazemos reverbera na eternidade.",
  "Seja consciente das suas escolhas diárias.",
  "Seus hábitos definem quem você será.",
  "Mude seus hábitos e mudará sua vida.",
  "Um por cento melhor a cada dia.",
  "Em um ano você será outra pessoa.",
  "A consistência é o segredo dos grandes.",
  "Não busque atalhos, busque fundamentos.",
  "Bases sólidas aguentam qualquer tempestade.",
  "Construa sua casa sobre a rocha.",
  "Segurança vem de dentro pra fora.",
  "Nada externo pode te abalar se o interno estiver firme.",
  "Mantenha-se centrado no seu propósito.",
  "O ruído do mundo é passageiro.",
  "A sua verdade é o que permanece.",
  "Seja autêntico até o fim.",
  "A máscara cai, a essência fica.",
  "Mostre sua vulnerabilidade, ela te humaniza.",
  "A força real vem de aceitar as fraquezas.",
  "Ninguém é perfeito e está tudo bem.",
  "Acolha suas imperfeições com carinho.",
  "E se esforce para evoluir onde puder.",
  "A jornada de mil milhas começa com um passo.",
  "Dê esse passo hoje, sem desculpas.",
  "O amanhã começa com o que você faz agora.",
  "Aproveite a vida com intensidade.",
  "Sinta cada momento como se fosse o último.",
  "A vida é uma dádiva maravilhosa.",
  "Agradeça, sempre agradeça.",
  "A gratidão é o ímã da abundância.",
  "Quanto mais você agradece, mais recebe.",
  "Seja grato por tudo, bom ou ruim.",
  "O mal vem para ensinar algo necessário.",
  "O bem vem para recompensar o esforço.",
  "Tudo coopera para o seu bem final.",
  "Confie no plano superior, ele é sábio.",
  "Você está exatamente onde deveria estar.",
  "O resto é história em construção.",
  "Mãos à obra e vamos criar o futuro!",
  "Acredite no impossível, ele só demora mais.",
  "Limites só existem na nossa cabeça.",
  "Quebre as barreiras mentais.",
  "Expanda seus horizontes sem medo.",
  "O universo é infinito e você também.",
  "Sinta a conexão com o todo.",
  "Somos todos um em essência.",
  "Trate o outro como a si mesmo.",
  "Amor é a resposta para todas as perguntas.",
  "Onde houver ódio, que eu leve o amor.",
  "A luz dissipa as trevas naturalmente.",
  "Seja luz, seja amor, seja vida.",
  "Tamo aqui pra isso kkk.",
  "Filosofia de boteco agora kkk.",
  "Bora trabalhar que a vida não para.",
  "Sucesso pra nós hoje e sempre!",
  "Fui, agora é sério kkk.",
  "Falou meu querido!",
  "Boa sorte aí nos seus projetos.",
  "Vou estar aqui torcendo por você.",
  "Depois me conta os resultados.",
  "Quero saber de tudo hein.",
  "Até a próxima interação!",
  "Valeu e tchau."
];

export const getRandomMessage = () => {
  const index = Math.floor(Math.random() * messageBank.length);
  return messageBank[index];
};
